services:
    publero_token_authentication.object_manager:
        class: Doctrine\ODM\MongoDB\DocumentManager
        factory_service: doctrine_mongodb
        factory_method: getManager
        arguments: [ '%publero_api_notification.storage.doctrine.model_manager_name%' ]
        public: false
