services:
    publero_api_notification.object_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManager
        arguments: [ '%publero_api_notification.storage.doctrine.model_manager_name%' ]
        public: false
