Publero\ApiNotificationBundle\Model\Notification:
    type: entity
    table: apinotificationbundle_notification
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
        data:
            type: text
        sentAt:
            type: datetime
            nullable: true
        scheduledAt:
            type: datetime
        sentCount:
            type: integer
