Publero\ApiNotificationBundle\Model\Notification:
    collection: publeroapinotification_notification
    fields:
        id:
            id: true
        code:
            type: string
        data:
            type: text
        sentAt:
            type: datetime
            nullable: true
        scheduledAt:
            type: datetime
        sentCount:
            type: integer
